config:
  MD003:
    style: atx
  MD013:
    line_length: 80
    tables: false
    code_blocks: false
  MD0014: false
  MD0040: false
  MD0060:
    style: aligned

globs:
  - "**/*.md"

fix: true

gitignore: true
