---
config:
  MD003:
    style: atx
  MD013:
    line_length: 80
    tables: false
    code_blocks: false
  MD014: false
  MD040: false
  MD060:
    style: aligned

globs:
  - "**/*.md"
ignores:
  - .claude/skills/caveman-commit/*

fix: true

gitignore: true
