---
- name: Configure RPi boards
  hosts: all

  vars:
    # List of channels with latest versions is available at
    # <https://update.k3s.io/v1-release/channels>.
    k3s_version: v1.36.3+k3s1

  roles:
    - role: packages
    - role: journald
    - role: zram
    - role: network
    - role: wireless
    - role: dns_resolver
    - role: wireguard
    - role: k3s
      when: inventory_hostname in groups['rpi4']
