---
- name: Configure RPI4
  hosts: all

  vars:
    # List of channels with latest versions is available at
    # <https://update.k3s.io/v1-release/channels>.
    k3s_version: v1.36.3+k3s1

  roles:
    - role: packages
    - role: journald
    - role: zram     # rpi4
    - role: network  # parameterize hostname
    - role: wireless  # wlan0.j2 parameterize IP address
    - role: dns_resolver
    - role: wireguard
    - role: k3s
