---
#
# Setup network
#

- name: Check network_hostname is set.
  delegate_to: localhost
  ansible.builtin.assert:
    that:
      - network_hostname | length > 0
    fail_msg: >
      network_hostname is empty. Set it via a group_vars file, see
      group_vars/rpi4/network.yml and group_vars/rpi3/network.yml.
    quiet: true
- name: Set hostname.
  become: true
  ansible.builtin.copy:
    content: "{{ network_hostname }}\n"
    dest: /etc/hostname
    owner: root
    group: root
    mode: '0644'
